project:
  type: book

book:
  title: "Polyglot programming for single-cell analysis"
  author:
    - "Louise Deconinck"
    - "Benjamin Rombaut"
    - "Robrecht Cannoodt"
  date: "9/12/2024"
  cover-image: assets/cover.svg
  chapters:
    - index.qmd
    - book/intro.qmd
    - notebooks/file_formats.qmd
    - notebooks/in_memory.qmd
    - notebooks/workflows.qmd
    - book/book_slides.qmd
    - book/references.qmd
    - notebooks/usecase.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    toc: true

# cache computations
execute:
  freeze: auto
