project:
  type: book

book:
  title: "Polyglot programming for single-cell analysis"
  author:
    - "Louise Deconinck"
    - "Benjamin Rombaut"
    - "Robrecht Cannoodt"
  date: "9/12/2024"
  cover-image: assets/cover.svg
  site-url: https://saeyslab.github.io/polygloty
  repo-url: https://github.com/saeyslab/polygloty
  repo-actions: [edit, issue, source]
  chapters:
    - index.qmd
    - book/introduction.qmd
    - book/usecase/index.qmd
    - book/inmemory/in_memory_interoperability.qmd
    - book/on_disk_interoperability.qmd
    - book/workflow_frameworks/index.qmd
    - book/book_slides.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    copy-code: true
    code-overflow: scroll

# cache computations
execute:
  freeze: auto
