project:
  type: book

book:
  title: "Polyglot programming for single-cell analysis"
  author:
    - name: Benjamin Rombaut
      orcid: 0000-0002-4022-715X
      affiliations:
        - name: Saeys lab
          city: Ghent
          country: Belgium
          url: https://saeyslab.sites.vib.be
        - name: VIB Center for Inflammation Research
          city: Ghent
          country: Belgium
        - department: Department of Applied Mathematics, Computer Science, and Statistics
          name: Ghent University
          city: Ghent
          country: Belgium
    - name: Louise Deconinck
      orcid: 0000-0001-8100-6823
      affiliations:
        - name: Saeys lab
          city: Ghent
          country: Belgium
          url: https://saeyslab.sites.vib.be
        - name: VIB Center for Inflammation Research
          city: Ghent
          country: Belgium
        - department: Department of Applied Mathematics, Computer Science, and Statistics
          name: Ghent University
          city: Ghent
          country: Belgium
    - name: Robrecht Cannoodt
      orcid: 0000-0003-3641-729X
      affiliations:
        - name: Data Intuitive
          city: Lebbeke
          country: Belgium
          url: https://data-intuitive.com
  date: "9/12/2024"
  cover-image: assets/cover.svg
  site-url: https://saeyslab.github.io/polygloty
  repo-url: https://github.com/saeyslab/polygloty
  repo-actions: [edit, issue, source]
  chapters:
    - index.qmd
    - book/introduction.qmd
    - book/usecase/index.qmd
    - text: "In-memory interoperability"
      part: book/in_memory/index.qmd
      chapters:
        - text: Pitfalls
          href: book/in_memory/pitfalls.qmd
        - text: rpy2
          href: book/in_memory/rpy2.qmd
        - text: reticulate
          href: book/in_memory/reticulate.qmd
    - book/on_disk_interoperability.qmd
    - text: Workflow frameworks
      part: book/workflow_frameworks/index.qmd
      chapters:
        - text: A review
          href: book/workflow_frameworks/review.qmd
        - text: Essential qualities and technologies
          href: book/workflow_frameworks/qualities.qmd
        - text: Quality assessment
          href: book/workflow_frameworks/quality_assessment.qmd
        - text: Example workflow
          href: book/workflow_frameworks/viash_nextflow.qmd
        - text: Best practices
          href: book/workflow_frameworks/best_practices.qmd
    - book/book_slides.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    copy-code: true
    code-overflow: scroll

# cache computations
execute:
  freeze: auto
