project:
  type: book

book:
  title: "Polyglot programming for single-cell analysis"
  author: 
    - "Louise Deconinck"
    - "Benjamin Rombaut"
    - "Robrecht Cannoodt"
  date: "9/12/2024"
  cover-image: book/cover.svg
  chapters:
    - index.qmd
    - book/intro.qmd
    - notebooks/file_formats.qmd
    - notebooks/anndataR.qmd
    - notebooks/workflows.qmd
    - book/references.qmd

bibliography: book/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
