name: compute_pseudobulk
description: Compute pseudobulk expression from anndata object

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --input
        description: Path to the input h5ad file
        example: /path/to/input.h5ad
        required: true
  - name: Pseudobulk arguments
    arguments:
      - type: string
        name: --obs_column_index
        description: Name of the column to pseudobulk on
        example: cell_type
        required: true
      - type: string
        name: --obs_column_values
        description: List of column names for the new obs data frame
        example: ["batch", "sample"]
        multiple: true
        required: true
  - name: Outputs
    arguments:
      - type: file
        name: --output
        description: Path to the output h5ad file
        example: /path/to/output.h5ad
        required: true
        direction: output

resources:
  - type: python_script
    path: script.py

test_resources:
  - type: python_script
    path: test.py

engines:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        pypi:
          - anndata
    test_setup:
      - type: python
        pypi:
          - viashpy

runners:
  - type: executable
  - type: nextflow